CREATE TABLE Songs
(SONG_ID        INT PRIMARY KEY   NOT NULL,
 NAME           CHARACTER(50)     NOT NULL,
 FILEPATH       TEXT              NOT NULL,
 ALBUM          CHARACTER(50),
 ARTIST         CHARACTER(50),
 LAST_PLAYED    DATE              DEFAULT GETDATE(),
 PLAY_COUNT     INTEGER           DEFAULT 0);
 
 CREATE TABLE MetaData
(SONG_ID        INT PRIMARY KEY   NOT NULL,
 NAME           CHARACTER(50)     NOT NULL,
 FILEPATH       TEXT              NOT NULL,
 ALBUM          CHARACTER(50),
 ARTIST         CHARACTER(50),
 LAST_PLAYED    DATE              DEFAULT GETDATE(),
 PLAY_COUNT     INTEGER           DEFAULT 0);